website/pet/urls.py
"""Linking urls"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show, name='show'),
    path('addpet/', views.addpet, name='addpet'),
    path('details/<petid>', views.details, name='details'),
    path('update/<petid>', views.update, name='update'),
    path('delete/<petid>',views.delete, name='delete'),
    path('contact/', views.contact, name='contact'),
]
# to access dog you would go to pet/

website/users/urls.py
"""User urls"""
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.sign_up, name='sign_up'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('pet.urls')),
    path('admin/', admin.site.urls),
    path('signup/', include('users.urls')),
    path('signin/', auth_views.LoginView.as_view(template_name='users/signin.html'),
    name='sign_in'),
    path('signout/', auth_views.LogoutView.as_view(template_name='users/signout.html'),
    name='sign_out'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/pet/models.py
"""Models file"""
from django.db import models

# Create your models here.


class Pet(models.Model):
    """Creating Pet database"""
    name = models.CharField(max_length=200)
    breed = models.CharField(max_length=200, default="")
    age = models.IntegerField()
    description = models.CharField(max_length=400, default="")
    image = models.ImageField(upload_to='images/', blank = True, null = True)

    def __str__(self):
        return self.name  + " "

website/users/models.py
"""User Models"""

# Create your models here.

website/pet/forms.py
"""Creating Pet Form"""
from django import forms
from django.forms import ModelForm
from .models import Pet

#create form here

class PetForm(ModelForm):
    """PETFORM"""
    class Meta:
        """Linking with models"""
        model = Pet
        fields = ('name','breed','age','description','image')
        labels = {
                'name':'',
                'breed':'',
                'age':'',
                'description':'',
                'image':'',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}),
            'age':forms.TextInput(attrs={'class':'form-control','placeholder':'Age'}),
            'breed':forms.TextInput(attrs={'class':'form-control','placeholder':'Breed'}),
            'description':forms.TextInput(attrs=
            {'class':'form-control','placeholder':'Description'}),
        }

website/users/forms.py
"""USERFORMS"""
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core import validators

class UserSignUpForm(UserCreationForm):
    """signupform"""
    email = forms.EmailField(validators=[validators.validate_email])
    min_length = 2
    max_length = 30
    message_lt_min = f"Should have at least {min_length} characters."
    message_ht_max = f"Should have at most{max_length} characters."
    name_regex='\A[a-zA-Z]+\Z'
    name_message='The name accepts only letters!'

    first_name = forms.CharField(validators=[
            validators.MinLengthValidator(min_length, message_lt_min),
            validators.MaxLengthValidator(max_length, message_ht_max),
            validators.RegexValidator(name_regex, name_message)
        ])
    last_name = forms.CharField(validators=[
            validators.MinLengthValidator(min_length),
            validators.MaxLengthValidator(max_length),
            validators.RegexValidator(name_regex, name_message)
        ])

class Meta:
    """META"""
    model = User
    fields = ['username', 'first_name',
        'last_name','email', 'password1', 'password2']

website/pet/views.py
"""Creating the Pet related views"""
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Pet
from .forms import PetForm
# Create your views here.

def index(request):
    return render(request, 'pet/index.html')

def show(request):
    pets = Pet.objects.all()
    return render(request, 'pet/pet.html', {"boi": pets})

def details(request, petid):
    pet = Pet.objects.get(pk=petid)
    return render(request, 'pet/details.html',{'pet': pet})

def update(request, petid):
    pet = Pet.objects.get(pk=petid)
    form = PetForm(request.POST or None, instance=pet)
    if form.is_valid():
        form.save()
        return redirect('show')
    return render(request, 'pet/update.html',{'pet': pet, 'form': form})

def delete(request, petid):
    pet = Pet.objects.get(pk=petid)
    pet.delete()
    return redirect('show')

def contact(request):
    """renders"""
    return render(request, 'pet/contact.html')


def addpet(request):
    """Function to add pet"""
    submitted = False
    if request.method == "POST":
        form = PetForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/pet/addpet?submitted=True')
    else:
        form = PetForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'pet/addpet.html', {'form': form, 'submitted': submitted})

website/users/views.py
"""user views"""
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserSignUpForm

def sign_up(request):
    """Usersignup"""
    if request.method == "POST":
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            un = form.cleaned_data.get('username')
            messages.success(request, 'Account created for {}.'.format(un))
            return redirect('sign_in')

    elif request.method == "GET":
        form = UserSignUpForm()

    return render(request, 'users/signup.html', {'form': form})

website/pet/templates/pet/addpet.html
{% extends "pet/base.html" %} 

{% block content %}
    <center>
        <h1> Add Pet for Adoption</h1>
        <br/><br/>
        {% if submitted %}
            Your entry was submitted succesfully.
        {% else %}
        
            <form action="" method=POST enctype = "multipart/form-data">
               {% csrf_token %}
               {{form.as_p}}
               
               <input type="submit" value="Submit" class ="btn btn-secondary">
            </form>    
    {% endif %}
    </center>
{% endblock %}

website/pet/templates/pet/base.html
<!DOCTYPE html>
<html lang="en">
  <style>
     body {
            background: linear-gradient(to right, #FFEEEE, #DDEFBB);
         }
     #nav{
       background:white;
     }
  </style>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Pet Life
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " id ='nav' style="colour:#ffffff ">
      <a class="navbar-brand" href="#"> Adopt a pet today </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'show' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'addpet' %}">Add a pet</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

website/pet/templates/pet/contact.html
{% extends "pet/base.html" %} {% block content %}
<br/><br/><br/><br/><br/>
<center>
    <br>
    <h1>Decided which one to take home? Contact us using either of the methods below: </h1>
    <br>
    <br>

    
    <h2>Tollfree Number: 1800-PET-3535</h2>
    <br>
    <br>
    <h2>Email: petadoption@xyz.com</h2>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    <blockquote class="blockquote text-center">
      <p class="mb-0">You can't buy love, but you can rescue it.</p>
      <footer class="blockquote-footer"> <cite title="Source Title">An anonymous pet owner</cite></footer>
    </blockquote>

</center>


{% endblock content %}

website/pet/templates/pet/details.html
{% extends "pet/base.html" %} {% block content %}

<center>
    <h1>{{ pet }} </h1>
    {{pet.age}} years old<br/>
    {{pet.description}}<br/>
    {{pet.breed}}<br/>
    <img src="{{pet.image.url}}" width = 100%>
    
</center>

{% endblock %}

website/pet/templates/pet/pet.html
{% extends "pet/base.html" %} {% block content %}
<h1> Pets </h1>
<style>
    img {
        float: left;
        width:  250px;
        height: 250px;
        object-fit: cover;
    }
    .container {
      display: flex;
      flex-wrap: wrap;
      align-items: stretch;
      
    }
    
    .card-text {
      flex: 1 0 auto;
      min-height:50px;
    }
    
    .card{
        margin-bottom:20px;
    }
    body {
            background: linear-gradient(to right, #FFEEEE, #DDEFBB);
         }
    .card-body{
        opacity: 0.7; 
    }
    .card-text{
        opacity: 1 !important;
        color: black;
        
    }


</style>
<body>
<div class="container">
<div class="row">
        {% for x in boi %}
            <div class="col-4">
                <div class="card" style="">
                <a href="{% url 'details' x.id %}" ><img src="{{ x.image.url }}" class="card-img-top"> </a>
                  <div class="card-body">
                    <h5 class="card-title">{{ x.name }}</h5>
                    <p class="card-text" >{{x.description}}</p>
                    <a href="{% url 'update' x.id %}" class="btn btn-outline-info">Update</a>
                    <a href="{% url 'delete' x.id %}" class="btn btn-outline-danger">Delete</a>
                  </div>
                </div>
            </div>
        {% endfor %}



{% endblock %}


</body>

website/pet/templates/pet/update.html
{% extends "pet/base.html" %} {% block content %}
<h1> Update </h1>
    <br />
    <form action="" method=POST>
        {%csrf_token%}
        {{form.as_p}}
        <br/>
        <input type="submit" value = "Update" class="btn btn-secondary">

{% endblock %}

website/users/templates/users/signin.html
{% extends "sign/base.html" %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
        <button type="submit">Sign In</button>
    </div>
    <p></p>
    <div>
        If you don't have an account yet
    <a href="{% url 'users:sign_up' %}">Sign Up</a>
    </div>
</form>

{% endblock content %}

website/users/templates/users/signout.html
<div>You have been signed out.<div>
<div><a href="{% url 'sign_in' %}">Sign In</a><div>

website/users/templates/users/signup.html
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }

    input[type="text"],
    input[type="email"],
    input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 3px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

    button[type="submit"]:hover {
        background-color: #0056b3;
    }

    .form-footer {
        margin-top: 10px;
        text-align: center;
    }

    .form-footer a {
        color: #007bff;
        text-decoration: none;
    }
</style>

<form method="POST">
    {% csrf_token %}
    <label for="id_username">Username:</label>
    {{ form.username }}
    <label for="id_email">Email:</label>
    {{ form.email }}
    <label for="id_password">Password:</label>
    {{ form.password }}
    <button type="submit">Sign Up</button>
    <div class="form-footer">
        If you have an account <a href="{% url 'sign_in' %}">Sign In</a>
    </div>
</form>







<!--<form method="POST">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <div>-->
<!--        <button type="submit">Sign Up</button>-->
<!--    </div>-->
<!--    <p></p>-->
<!--    <div>-->
<!--        If you have an account <a href="{% url 'sign_in' %}">Sign In</a>-->
<!--    </div>-->
<!--</form>-->